/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author JAGDEV RAJPOOT
 */
public class welcome extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    String sgid;
    public welcome() {
        initComponents();
    }
    public welcome(String g_id)
    {
        initComponents();
         sgid=g_id;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        entry1 = new javax.swing.JButton();
        history1 = new javax.swing.JButton();
        return1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Welcome In Vehicle Managment System");

        entry1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        entry1.setForeground(new java.awt.Color(204, 0, 0));
        entry1.setText("Entry Vehicle");
        entry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entry1ActionPerformed(evt);
            }
        });

        history1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        history1.setForeground(new java.awt.Color(102, 0, 0));
        history1.setText("Show History");
        history1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                history1ActionPerformed(evt);
            }
        });

        return1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        return1.setForeground(new java.awt.Color(204, 0, 0));
        return1.setText("Return Vehicle");
        return1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(entry1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(return1)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(history1)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entry1)
                    .addComponent(return1))
                .addGap(50, 50, 50)
                .addComponent(history1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entry1ActionPerformed
        // TODO add your handling code here:
        java.sql.Date sqlDate = new java.sql.Date(new java.util.Date().getTime());
 //System.out.println(sqlDate);
        
            SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss");
	    Date date = new Date();
                Date date1 = Calendar.getInstance().getTime();  
                DateFormat dateFormat = new SimpleDateFormat("yyyy-M-dd");  
                String d = dateFormat.format(date1);  
           String time=formatter.format(date);
          
         enter f2 = new enter(d,time,sgid);
           f2.show();
    }//GEN-LAST:event_entry1ActionPerformed

    private void history1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_history1ActionPerformed
        // TODO add your handling code here:
        try
       {
           Connection con=null;
           
            Class.forName("com.mysql.jdbc.Driver");

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/jagdev?zeroDateTimeBehavior=convertToNull","root","");

            PreparedStatement ps = con.prepareStatement("select v_no from history");

            ResultSet rs = ps.executeQuery();

            Vector v = new Vector();
             
            while (rs.next()) {

                String s = rs.getString(1);
                 v.add(s);
            }
            
             JComboBox bx;
             bx = new JComboBox(v);
           
            JFrame frame = new JFrame("Select Vehicle Number");
            final JList list = new JList(bx.getModel());
               
          bx.addActionListener(new ActionListener() {
           
          public void actionPerformed(ActionEvent ae) {
              
              JComboBox cb = (JComboBox)ae.getSource();
             String s = (String)bx.getSelectedItem();
             //System.out.println(s);
            history h1 = new history(s);
            h1.show();
          }
        });

        
        Container c = frame.getContentPane();  
        JPanel comboPanel = new JPanel();
        comboPanel.add(bx);
        c.add(comboPanel, BorderLayout.NORTH);
        c.add(new JScrollPane(list), BorderLayout.CENTER);
        
        frame.setSize(200, 200);
        frame.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );
        frame.setVisible(true);
            con.close();
       }
    catch (Exception e)
    {
      //System.err.println("Got an exception!");
        //System.out.println("hello.............");
      System.err.println(e.getMessage());
    }
    }//GEN-LAST:event_history1ActionPerformed

    private void return1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return1ActionPerformed
        // TODO add your handling code here:
         SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss");
	    Date date = new Date();
                Date date1 = Calendar.getInstance().getTime();  
                DateFormat dateFormat = new SimpleDateFormat("yyyy-M-dd");  
                String d = dateFormat.format(date1);  
           String time=formatter.format(date);
        return_vehicle r1 = new return_vehicle(sgid,time);
        r1.show();
    }//GEN-LAST:event_return1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entry1;
    private javax.swing.JButton history1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton return1;
    // End of variables declaration//GEN-END:variables

    private void history(Vector v) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void history(String s) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
